### ISSUE TITLE
In memory repository

### ISSUE THREAD

**Issue by EnderCrypt** [EnderCrypt/JaxRs-lab#1]
we need a in memory repository that doesent communicate with the database

this is to speed up the development and eliminate potential problems with database connections that we may or may not have

this includes in memory repositories for team/user/item/issue

you problably wanna use an arrayList to store entries (since ArrayList has Id)

**Comment by MelEnt** [comment]
assigned to Eduard.
hint:
- currently, TeamIssue saves entities (teamRepo.save(entity)) to the instance of getBean(TeamRepository), so to achieve a current flow to an in memory repository it is required that each service operates (CRUD) to an ArrayList

ex:
current:
TeamRepository teamRepo = getBean(TeamRepository.class)
teamRepo.save(entity)
teamRepo.findOne(id)

requested:
List<Team> teams = new ArrayList<>()
teams.add(entity)
teams.get(entity)

**Comment by EnderCrypt** [comment]
this will no longer be needed, closed
